# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2019-03-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField()),
            ],
        ),
    ]
